daily = read.csv("dailykos.csv")
str(daily)
distances = dist(daily, method="euclidean")
clust = hclust(distances, method="ward.D")
plot(clust)
rect.hclust(clust, 7)
groups = cutree(clust, 7)
clusters = split(daily, groups)
nrow(clusters[[3]])
lapply(clusters, nrow)
lapply(lapply(lapply(clusters, colMeans), sort), tail)

# kmeans
set.seed(1000)
KMC = kmeans(daily, centers=7)
kmcClusters = split(daily, KMC$cluster)
lapply(kmcClusters, nrow)
lapply(lapply(lapply(kmcClusters, colMeans), sort), tail)

table(groups, KMC$cluster)
