daily = read.csv("dailykos.csv")
str(daily)
distances = dist(daily, method="euclidean")
clust = hclust(distances, method="ward.D")
plot(clust)
rect.hclust(clust, 7)
groups = cutree(clust, 7)
clusters = split(daily, groups)
nrow(clusters[[3]])
lapply(clusters, nrow)
lapply(lapply(lapply(clusters, colMeans), sort), tail)
