stocks = read.csv("StocksCluster.csv")
str(stocks)
table(stocks$PositiveDec)
6324/nrow(stocks)
cor(stocks)
summary(stocks)

library(caTools)
set.seed(144)
spl = sample.split(stocks$PositiveDec, SplitRatio=0.7)
stockTrain = subset(stocks, spl==T)
stockTest = subset(stocks, spl==F)
modLog= glm(PositiveDec ~ ., data=stockTrain, family=binomial)
summary(modLog)
predTrainLog= predict(modLog, type="response")
tableTrainLog= table(stockTrain$PositiveDec, predTrainLog> 0.5)
sum(diag(1,2)*tableTrainLog)/sum(tableTrainLog)

predTestLog = predict(modLog, newdata=stockTest, type="response")
tableTestLog = table(stockTest$PositiveDec, predTestLog > 0.5)
sum(diag(1,2)*tableTestLog)/sum(tableTestLog)
