library(tm)
library(SnowballC)
library(wordcloud)

tweets = read.csv("tweets.csv", stringsAsFactors=F)
corpus = Corpus(VectorSource(tweets$Tweet))
corpus = tm_map(corpus, tolower)
corpus = tm_map(corpus, PlainTextDocument)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, stopwords("english"))
dtm = DocumentTermMatrix(corpus)
allTweets = as.data.frame(as.matrix(dtm))
ncol(allTweets)
wordcloud(colnames(allTweets), colSums(allTweets), scale=c(2, 0.25))

corpus = Corpus(VectorSource(tweets$Tweet))
corpus = tm_map(corpus, tolower)
corpus = tm_map(corpus, PlainTextDocument)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, c(stopwords("english"), "apple")) 
dtm = DocumentTermMatrix(corpus)
allTweets = as.data.frame(as.matrix(dtm))
ncol(allTweets)
wordcloud(colnames(allTweets), colSums(allTweets), scale=c(2, 0.25))
  

negativeTweets = subset(allTweets, tweets$Avg <= -1)
wordcloud(colnames(negativeTweets), colSums(negativeTweets), colors=brewer.pal(9, "Blues"))
wordcloud(colnames(allTweets), colSums(allTweets), colors=brewer.pal(9, "Blues")
)